/*
PROMPT:
create some HTML or Javascript code that adds the functionality of a menu to my existing php web page. it shall be optimized for mobile phones and uses bootstrap.
by default it shall be very compact and only very little shall be visible until the users clicks on the hamburger menu button. 

Ideally, I want to put your new code into a separate file. in the existing file, I only want to add a single line of code to add the functionality.

The menu items shall be generated from a array:
("geraete_verwaltung.php", "Geräte Verwaltung"),
("geraetetypen_verwaltung.php", "Gerätetypen Verwaltung"),
 ("durchgaenge.php", "Durchgänge Verwaltung")


on page creation, the active item shall be generated by setting the properties of the "a-tag"
          <a class="nav-link active" aria-current="page" href="#">
accordingly. the active item shall be found via the called URL.


----
Additional Notes:

<!-- In your PHP file, add this single line where you want the menu to load -->
  <script src="menu.js"></script>

Bootstrap Dependency:
Ensure that your project includes the proper Bootstrap CSS and JavaScript files. For example, in your <head> section you might add:
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
And just before the closing </body> tag:
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>


*/

(function() {
  const menuItems = [
    { href: "index.php", label: "Start" },
    { href: "riegen.php", label: "Riegen" },
    { href: "kari.php", label: "Kari-Wertungseingabe" },
    { href: "ergebnisse.php", label: "Wettkampf Ergebnisse" },
    { href: "geraete_verwaltung.php", label: "Geräte" },
    { href: "geraetetypen_verwaltung.php", label: "Gerätetypen" },
    { href: "durchgaenge.php", label: "Durchgänge" },
    { href: "riegen_verwaltung.php", label: "Riegen Verwaltung" },
    { href: "durchgaenge_zuordnung.php", label: "Riegen <-> Geräte <-> Durchgänge" },
    { href: "wettkaempfe_verwaltung.php", label: "Wettkämpfe" },
    { href: "vereine_verwaltung.php", label: "Vereine" },
    { href: "turner_verwaltung.php", label: "Turner" },
    { href: "wertungen.php", label: "Wertungen" }
  ];

  const getCurrentFile = () => {
    const file = window.location.pathname.split('/').pop();
    return file && file.length > 0 ? file : 'index.php';
  };

  const buildNavList = (currentFile) => {
    return menuItems.map(item => {
      const isActive = item.href === currentFile;
      const activeClass = isActive ? ' active' : '';
      return `<li><a class="tw-nav-link${activeClass}" href="${item.href}">${item.label}</a></li>`;
    }).join('');
  };

  const ensureStyles = () => {
    if (document.getElementById('tw-menu-styles')) return;
    const style = document.createElement('style');
    style.id = 'tw-menu-styles';
    style.textContent = `
      :root {
        --tw-sidebar-width: 250px;
        --tw-sidebar-bg: #111827;
        --tw-sidebar-text: #e5e7eb;
        --tw-sidebar-muted: #9ca3af;
        --tw-sidebar-accent: #10b981;
      }
      body.tw-has-sidebar {
        padding-left: var(--tw-sidebar-width);
      }
      #tw-sidebar {
        position: fixed;
        inset: 0 auto 0 0;
        width: var(--tw-sidebar-width);
        background: var(--tw-sidebar-bg);
        color: var(--tw-sidebar-text);
        z-index: 1040;
        display: flex;
        flex-direction: column;
        padding: 16px;
        gap: 12px;
      }
      #tw-sidebar .tw-brand {
        font-size: 1.1rem;
        font-weight: 700;
        letter-spacing: 0.02em;
      }
      #tw-sidebar .tw-sub {
        color: var(--tw-sidebar-muted);
        font-size: 0.85rem;
      }
      .tw-nav {
        list-style: none;
        padding: 0;
        margin: 8px 0 0 0;
        display: grid;
        gap: 6px;
      }
      .tw-nav-link {
        display: block;
        padding: 10px 12px;
        border-radius: 10px;
        color: var(--tw-sidebar-text);
        text-decoration: none;
        font-size: 0.95rem;
      }
      .tw-nav-link:hover {
        background: rgba(255,255,255,0.08);
        color: #fff;
      }
      .tw-nav-link.active {
        background: var(--tw-sidebar-accent);
        color: #052e1d;
        font-weight: 600;
      }
      #tw-mobile-toggle {
        position: fixed;
        top: 12px;
        left: 12px;
        z-index: 1050;
        display: none;
        border-radius: 10px;
      }
      .tw-offcanvas {
        background: var(--tw-sidebar-bg);
        color: var(--tw-sidebar-text);
      }
      .tw-offcanvas .tw-nav-link {
        color: var(--tw-sidebar-text);
      }
      .tw-offcanvas .tw-nav-link.active {
        background: var(--tw-sidebar-accent);
        color: #052e1d;
      }
      @media (max-width: 991px) {
        body.tw-has-sidebar {
          padding-left: 0;
        }
        #tw-sidebar {
          display: none;
        }
        #tw-mobile-toggle {
          display: inline-flex;
        }
      }
    `;
    document.head.appendChild(style);
  };

  const initMenu = () => {
    const currentFile = getCurrentFile();
    ensureStyles();

    if (!document.body.classList.contains('tw-has-sidebar')) {
      document.body.classList.add('tw-has-sidebar');
    }

    if (!document.getElementById('tw-sidebar')) {
      const sidebar = document.createElement('aside');
      sidebar.id = 'tw-sidebar';
      sidebar.innerHTML = `
        <div>
          <div class="tw-brand">Turnwettkampf</div>
          <div class="tw-sub">Verwaltung</div>
        </div>
        <nav>
          <ul class="tw-nav">
            ${buildNavList(currentFile)}
          </ul>
        </nav>
      `;
      document.body.insertAdjacentElement('afterbegin', sidebar);
    }

    if (!document.getElementById('tw-mobile-toggle')) {
      const btn = document.createElement('button');
      btn.id = 'tw-mobile-toggle';
      btn.className = 'btn btn-dark';
      btn.type = 'button';
      btn.setAttribute('data-bs-toggle', 'offcanvas');
      btn.setAttribute('data-bs-target', '#tw-offcanvas');
      btn.setAttribute('aria-controls', 'tw-offcanvas');
      btn.innerHTML = 'Menü';
      document.body.appendChild(btn);
    }

    if (!document.getElementById('tw-offcanvas')) {
      const offcanvas = document.createElement('div');
      offcanvas.className = 'offcanvas offcanvas-start tw-offcanvas';
      offcanvas.id = 'tw-offcanvas';
      offcanvas.tabIndex = -1;
      offcanvas.setAttribute('aria-labelledby', 'tw-offcanvas-label');
      offcanvas.innerHTML = `
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="tw-offcanvas-label">Menü</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Schließen"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="tw-nav">
            ${buildNavList(currentFile)}
          </ul>
        </div>
      `;
      document.body.appendChild(offcanvas);
    }
  };

  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', initMenu);
  } else {
    initMenu();
  }
})();

